# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://Journerist.github.io/nbdev_playground/"

git_url = "https://github.com/Journerist/nbdev_playground/tree/master/"

def custom_doc_links(name): return None
